name: build
run-name: Jekyll Contentful Build and Deploy
on:
  workflow_call:
    secrets:
      ACTIONS_DEPLOY_KEY:
        description: GitHub Deploy Key
      TEK_TEST_CONTENTFUL_SPACE_ID:
        description: 'Contentful Space ID passed from the build-on-publish.yml workflow'
        required: true
      TEK_TEST_CONTENTFUL_ACCESS_TOKEN:
        description: 'Contentful Access Token passed from the build-on-publish.yml workflow'
        required: true
  push:
    branches: [ main ]
env:
  ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
  TEK_TEST_CONTENTFUL_SPACE_ID: ${{ secrets.TEK_TEST_CONTENTFUL_SPACE_ID }}
  TEK_TEST_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.TEK_TEST_CONTENTFUL_ACCESS_TOKEN }}
jobs:
  pull-build-deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby-version: [3.1.2]
        node-version: [18.9.0]
    steps:
      - uses: actions/checkout@v4
      - name: Update Main Branch
        run: git pull origin main
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install bundler
        run: gem install bundler 
      - name: Install dependencies
        run: bundle install
      - name: Pull data from Contentful
        run: bundle exec jekyll contentful
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./_site